server: 
  port: 3344 
  
spring:
  application:
    name: springCloud-config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:jonay930128/springCloud-config-demo.git #GitHub上面的git仓库名字

