server:
  port: 9528

spring:
  application:
    name: zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/ #http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: gateway-9528.com
    prefer-ip-address: true


zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  #ignored-services: microservicecloud-dept
  prefix: /wrx
  ignored-services: "*"
  routes:
    myProvider.serviceId: provider
    myProvider.path: /myProvider/**

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000