spring:
  application:
    name: springboot-admin
server:
  port: 8307


eureka:
  instance:
    prefer-ip-address: true # 注册服务的时候使用服务的ip地址
    instance-id: springboot-admin
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/ #http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

